version: "3"

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: estacionai
    ports:
      - "3036:3036"

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  mysql-data:
