version: "3.7"

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: estacionai
    ports:
      - "3306:3306"

  app:
    build: .
    command: bash -c "npx prisma migrate dev && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      
    depends_on:
      - db

volumes:
  mysql-data:
